name: Anathema TUI
run-name: ${{ github.actor }} running CI/CD
on: 
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: test
        run: cargo test
      - name: lint
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy
